# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Brook's Room
subtitle: 一个逼格的程序猿、码农。
description: "用心关注 细心聆听 努力做好每一天"
keywords: "IT,java,node,前端,HTML5,javascript,音乐"
author: Shaojun Liu
email: me@imjun.me
language: zh-Hans # zn-CN
timezone:
favicon: /favicon.ico
# 站点起始时间
since: 2015
# 访客数统计
counter: true
# ---------------------------------------------
# 社交链接，将在侧栏中显示
#----------------------------------------------
# Social Icons
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  Twitter: twitter
  Weibo: weibo
  Email: envelope
  ZhiHu: zhihu
social:
  GitHub: http://github.com/liushaojun
  Twitter: your-twitter-url
  Weibo: http://www.weibo.com/imshaojun
  # DouBan: your-douban-url
  ZhiHu: http://www.zhihu.com/people/liu-shao-jun-14
  Email: mailTo:liushaojunvip@sina.com
# 配置代码高亮
highlight:
  enable: true
  backtick_code_block: true
  line_number: true
  tab_replace:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://imjun.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
# Category & Tag
default_category: uncategorized
category_map:
tag_map:
  archive: 1
  category: 1
  tag: 1

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next #modernist


# MathJax Support
mathjax:


# Swiftype Search API Key
swiftype_key: Jy6V-D4qVFSMdS6g9hYc  #

# Baidu Analytics ID
baidu_analytics: daf9a80804a314098db0bab59dbdb09d

# Duoshuo ShortName
duoshuo_shortname: imjun
# 多说热评文章
duoshuo_hotartical: true
# Disqus
#disqus_shortname:

# Share
jiathis: false

# Share
duoshuo_share: true

links_title: Links
# links
links:
  MacTalk: http://macshuo.com/
  LongShao: http://jinyunlong.github.io/
  TouTiao: http://toutiao.io/
  StackOverflow: http://stackoverflow.com/
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
#google_site_verification:
# google-site-verification=rrScp3LLhpzTZ4mnby9KqCd8h2p67w4Cr7YfvP6iPYU   谷歌dns 验证

bing_site_verification: 49DFB724F74211398C07F489614D9FB8
# Google Analytics
#google_analytics:
baidu_site_verification: Uw8cHh5ht2

# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
# duoshuo_info:
#   ua_enable: true
#   admin_enable: false
#   user_id: 0
  #admin_nickname: ROOT


# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# Deployment
## Docs: http://hexo.io/docs/deployment.html
#
#Plugins
plugins:
- hexo-generator-feed
- hexo-generator-sitemap
#feed sitemap
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
sitemap:
  path: sitemap.xml

plugins:
  - hexo-qiniu-sync

# #七牛云存储设置
# ##offline       是否离线. 离线状态将使用本地地址渲染
# ##sync          是否同步
# ##bucket        空间名称.
# ##access_key    上传密钥AccessKey
# ##secret_key    上传密钥SecretKey
# ##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步 
# ##urlPrefix     外链前缀. 
# ##local_dir     本地目录.
# ##update_exist  是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
# ##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
# ##image.extend  这是个特殊参数，用于生成缩略图或加水印等操作。具体请参考http://developer.qiniu.com/docs/v6/api/reference/fop/image/ 
# ##              可使用基本图片处理、高级图片处理、图片水印处理这3个接口。例如 ?imageView2/2/w/500 即生成宽度最多500px的缩略图
qiniu:
  offline: false
  sync: true
  bucket: static
  access_key: FVuAO6TmCXOaEoGl1-CMou5_FVQTOORXLajqnzIO
  secret_key: nEswfz9MPBRSQPfYm-mW-xc_ZgMdq_1kQee8Pr6L
  dirPrefix: static
  urlPrefix: https://dn-imjun.qbox.me/
  local_dir: static
  update_exist: true
  image: 
    folder: images
    extend: -wm
  js:
    folder: js
  css:
    folder: css
deploy:
  type: git
  repository: 
    github: https://github.com/liushaojun/liushaojun.github.io.git,master
    gitcafe: https://git.coding.net/ishaojun/brook.git,coding-pages

